name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: registry.moonrhythm.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - uses: docker/build-push-action@v4
        with:
          provenance: false
          push: true
          tags: |
            registry.moonrhythm.io/deploys-app/cloudflare-syncer:${{ github.sha }}
